@api = http://localhost:4000/mesero

//buscar
GET  {{api}}


###
//
POST {{api}}
Content-Type: application/json

{
  "platillo": "perro",
  "cantidad": 1,
  "cliente": "juan",
  "precio": 16000,
  "observaciones": "poca salsa",
  "estado": "pedido"
}

###
PUT {{api}}
Content-Type: application/json

{
  "id_pedido": 53,
  "estado": "prueba"
}


###
DELETE {{api}}
Content-Type: application/json

{
  "id_pedido":50
}